-- AXIA DESKTOP FIX18
-- Cotizaciones comerciales formales con folio COT-XXXXX.
-- Ejecutar UNA SOLA VEZ en Supabase SQL Editor antes de usar FIX18.

create sequence if not exists public.seq_cotizaciones_folio start with 1 increment by 1;

create table if not exists public.db_cotizaciones (
    id_cotizacion bigint generated by default as identity primary key,
    cot_folio text not null unique,
    id_levantamiento bigint,
    lev_folio text not null,
    id_cliente bigint,
    cot_cliente text,
    id_sucursal bigint,
    cot_sucursal text,
    cot_contacto text,
    cot_asunto text,
    cot_fecha date not null default current_date,
    cot_esi text,
    cot_esi_correo text,
    cot_esi_telefono text,
    cot_jefe_operaciones text,
    cot_supervisor text,
    cot_dias text,
    cot_personas text,
    cot_plan_pagos text,
    cot_vigencia text,
    cot_descuento_pct numeric(7,2) not null default 0,
    cot_iva_pct numeric(7,2) not null default 16,
    cot_partidas_json jsonb not null default '[]'::jsonb,
    cot_subtotal numeric(14,2) not null default 0,
    cot_descuento numeric(14,2) not null default 0,
    cot_subtotal_descuento numeric(14,2) not null default 0,
    cot_iva numeric(14,2) not null default 0,
    cot_total numeric(14,2) not null default 0,
    cot_estatus text not null default 'BORRADOR',
    creado_por text,
    actualizado_por text,
    fecha_registro timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now()
);

create index if not exists idx_db_cotizaciones_lev_folio
    on public.db_cotizaciones (lev_folio, fecha_actualizacion desc);
create index if not exists idx_db_cotizaciones_cliente
    on public.db_cotizaciones (id_cliente, fecha_actualizacion desc);
create index if not exists idx_db_cotizaciones_folio
    on public.db_cotizaciones (cot_folio);

-- Alinea la secuencia con folios existentes si la migración se aplica sobre una base restaurada.
select setval(
    'public.seq_cotizaciones_folio',
    greatest(
        1,
        coalesce((select max((regexp_match(cot_folio, '^COT-([0-9]+)$'))[1]::bigint) from public.db_cotizaciones), 0)
    ),
    coalesce((select count(*) > 0 from public.db_cotizaciones), false)
);

create or replace function public.generar_folio_cotizacion()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
    n bigint;
begin
    n := nextval('public.seq_cotizaciones_folio');
    return 'COT-' || lpad(n::text, 5, '0');
end;
$$;

grant execute on function public.generar_folio_cotizacion() to anon, authenticated, service_role;

comment on table public.db_cotizaciones is
    'Cotizaciones comerciales generadas desde levantamientos preautorizados.';
comment on column public.db_cotizaciones.cot_partidas_json is
    'Detalle comercial: proveedor, modelo, SKU, marca, precios, utilidad, importe y observaciones.';
