-- =============================================================
-- AXIA BETA 0.95 - SINCRONIZACIÓN SUPABASE V2
-- Fecha: 2026-07-15
-- No destructiva e idempotente.
--
-- Corrige el diagnóstico anterior:
--   * db_obras_civiles NO existe: se crea completa.
--   * db_ordenes_trabajo NO existe: se crea completa.
--   * db_clientes_sucursales: agrega suc_estado y suc_municipio.
--   * db_usuarios: agrega usu_correo.
-- =============================================================

BEGIN;

-- -------------------------------------------------------------
-- 1. COLUMNAS EN TABLAS EXISTENTES
-- -------------------------------------------------------------
ALTER TABLE IF EXISTS public.db_clientes_sucursales
    ADD COLUMN IF NOT EXISTS suc_estado text,
    ADD COLUMN IF NOT EXISTS suc_municipio text;

ALTER TABLE IF EXISTS public.db_usuarios
    ADD COLUMN IF NOT EXISTS usu_correo text;

-- -------------------------------------------------------------
-- 2. TABLA DE OBRAS CIVILES
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.db_obras_civiles (
    obc_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obc_folio text NOT NULL,
    obc_fecha date,
    obc_aco_numero text,
    obc_cliente text,
    obc_contacto text,
    obc_sucursal text,
    obc_direccion text,
    obc_responsable_axia text,
    obc_supervisor text,
    obc_tipo_giro text,
    obc_nombre_proyecto text,
    obc_superficie_disponible text,
    obc_superficie_adecuada text,
    obc_planos_arquitectonicos text,
    obc_requiere_maquinaria text,
    obc_permisos text,
    obc_observaciones_iniciales text,
    obc_ejecucion_json jsonb DEFAULT '{}'::jsonb,
    obc_pruebas_resultado text,
    obc_pruebas_observaciones text,
    obc_planos_acabados text,
    obc_generacion_planos text,
    obc_etapa_acabados text,
    obc_obra_blanca text,
    obc_evidencias_json jsonb DEFAULT '[]'::jsonb,
    obc_preentrega_resultado text,
    obc_preentrega_observaciones text,
    obc_entrega_formal text,
    obc_fecha_entrega date,
    obc_observaciones_finales text,
    obc_firma_cliente_base64 text,
    obc_firma_tecnico_base64 text,
    obc_estatus integer NOT NULL DEFAULT 1,
    creado_por text,
    fecha_registro timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Agrega columnas si la tabla ya existía parcialmente.
ALTER TABLE public.db_obras_civiles
    ADD COLUMN IF NOT EXISTS obc_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS obc_folio text,
    ADD COLUMN IF NOT EXISTS obc_fecha date,
    ADD COLUMN IF NOT EXISTS obc_aco_numero text,
    ADD COLUMN IF NOT EXISTS obc_cliente text,
    ADD COLUMN IF NOT EXISTS obc_contacto text,
    ADD COLUMN IF NOT EXISTS obc_sucursal text,
    ADD COLUMN IF NOT EXISTS obc_direccion text,
    ADD COLUMN IF NOT EXISTS obc_responsable_axia text,
    ADD COLUMN IF NOT EXISTS obc_supervisor text,
    ADD COLUMN IF NOT EXISTS obc_tipo_giro text,
    ADD COLUMN IF NOT EXISTS obc_nombre_proyecto text,
    ADD COLUMN IF NOT EXISTS obc_superficie_disponible text,
    ADD COLUMN IF NOT EXISTS obc_superficie_adecuada text,
    ADD COLUMN IF NOT EXISTS obc_planos_arquitectonicos text,
    ADD COLUMN IF NOT EXISTS obc_requiere_maquinaria text,
    ADD COLUMN IF NOT EXISTS obc_permisos text,
    ADD COLUMN IF NOT EXISTS obc_observaciones_iniciales text,
    ADD COLUMN IF NOT EXISTS obc_ejecucion_json jsonb DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS obc_pruebas_resultado text,
    ADD COLUMN IF NOT EXISTS obc_pruebas_observaciones text,
    ADD COLUMN IF NOT EXISTS obc_planos_acabados text,
    ADD COLUMN IF NOT EXISTS obc_generacion_planos text,
    ADD COLUMN IF NOT EXISTS obc_etapa_acabados text,
    ADD COLUMN IF NOT EXISTS obc_obra_blanca text,
    ADD COLUMN IF NOT EXISTS obc_evidencias_json jsonb DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS obc_preentrega_resultado text,
    ADD COLUMN IF NOT EXISTS obc_preentrega_observaciones text,
    ADD COLUMN IF NOT EXISTS obc_entrega_formal text,
    ADD COLUMN IF NOT EXISTS obc_fecha_entrega date,
    ADD COLUMN IF NOT EXISTS obc_observaciones_finales text,
    ADD COLUMN IF NOT EXISTS obc_firma_cliente_base64 text,
    ADD COLUMN IF NOT EXISTS obc_firma_tecnico_base64 text,
    ADD COLUMN IF NOT EXISTS obc_estatus integer DEFAULT 1,
    ADD COLUMN IF NOT EXISTS creado_por text,
    ADD COLUMN IF NOT EXISTS fecha_registro timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- Los tres identificadores toman automáticamente el tipo de sus tablas origen.
DO $$
DECLARE tipo text;
BEGIN
    SELECT format_type(a.atttypid, a.atttypmod) INTO tipo
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname='public' AND c.relname='db_acos'
      AND a.attname='id_aco' AND a.attnum > 0 AND NOT a.attisdropped;
    EXECUTE format('ALTER TABLE public.db_obras_civiles ADD COLUMN IF NOT EXISTS id_aco %s', COALESCE(tipo, 'text'));

    SELECT format_type(a.atttypid, a.atttypmod) INTO tipo
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname='public' AND c.relname='db_clientes_sucursales'
      AND a.attname='suc_id' AND a.attnum > 0 AND NOT a.attisdropped;
    EXECUTE format('ALTER TABLE public.db_obras_civiles ADD COLUMN IF NOT EXISTS id_sucursal %s', COALESCE(tipo, 'text'));

    SELECT format_type(a.atttypid, a.atttypmod) INTO tipo
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname='public' AND c.relname='db_clientes_sucursal_contactos'
      AND a.attname='con_id' AND a.attnum > 0 AND NOT a.attisdropped;
    EXECUTE format('ALTER TABLE public.db_obras_civiles ADD COLUMN IF NOT EXISTS id_contacto %s', COALESCE(tipo, 'text'));
END $$;

-- -------------------------------------------------------------
-- 3. TABLA DE ÓRDENES DE TRABAJO
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.db_ordenes_trabajo (
    ot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ot_folio text NOT NULL,
    ot_fecha date,
    ot_aco_numero text,
    ot_cliente text,
    ot_contacto text,
    ot_sucursal text,
    ot_jefe_operacion text,
    ot_supervisor text,
    ot_esi text,
    ot_numero_dias text,
    ot_numero_personas text,
    ot_asunto text,
    ot_partidas_json jsonb DEFAULT '[]'::jsonb,
    ot_descripcion text,
    ot_estatus integer NOT NULL DEFAULT 1,
    ot_prioridad integer NOT NULL DEFAULT 2,
    creado_por text,
    fecha_registro timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.db_ordenes_trabajo
    ADD COLUMN IF NOT EXISTS ot_id bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS ot_folio text,
    ADD COLUMN IF NOT EXISTS ot_fecha date,
    ADD COLUMN IF NOT EXISTS ot_aco_numero text,
    ADD COLUMN IF NOT EXISTS ot_cliente text,
    ADD COLUMN IF NOT EXISTS ot_contacto text,
    ADD COLUMN IF NOT EXISTS ot_sucursal text,
    ADD COLUMN IF NOT EXISTS ot_jefe_operacion text,
    ADD COLUMN IF NOT EXISTS ot_supervisor text,
    ADD COLUMN IF NOT EXISTS ot_esi text,
    ADD COLUMN IF NOT EXISTS ot_numero_dias text,
    ADD COLUMN IF NOT EXISTS ot_numero_personas text,
    ADD COLUMN IF NOT EXISTS ot_asunto text,
    ADD COLUMN IF NOT EXISTS ot_partidas_json jsonb DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS ot_descripcion text,
    ADD COLUMN IF NOT EXISTS ot_estatus integer DEFAULT 1,
    ADD COLUMN IF NOT EXISTS ot_prioridad integer DEFAULT 2,
    ADD COLUMN IF NOT EXISTS creado_por text,
    ADD COLUMN IF NOT EXISTS fecha_registro timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

DO $$
DECLARE tipo text;
BEGIN
    SELECT format_type(a.atttypid, a.atttypmod) INTO tipo
    FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relname='db_acos' AND a.attname='id_aco' AND a.attnum>0 AND NOT a.attisdropped;
    EXECUTE format('ALTER TABLE public.db_ordenes_trabajo ADD COLUMN IF NOT EXISTS id_aco %s', COALESCE(tipo, 'text'));

    SELECT format_type(a.atttypid, a.atttypmod) INTO tipo
    FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relname='db_clientes_sucursales' AND a.attname='suc_id' AND a.attnum>0 AND NOT a.attisdropped;
    EXECUTE format('ALTER TABLE public.db_ordenes_trabajo ADD COLUMN IF NOT EXISTS id_sucursal %s', COALESCE(tipo, 'text'));

    SELECT format_type(a.atttypid, a.atttypmod) INTO tipo
    FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relname='db_clientes_sucursal_contactos' AND a.attname='con_id' AND a.attnum>0 AND NOT a.attisdropped;
    EXECUTE format('ALTER TABLE public.db_ordenes_trabajo ADD COLUMN IF NOT EXISTS id_contacto %s', COALESCE(tipo, 'text'));
END $$;

-- -------------------------------------------------------------
-- 4. ÍNDICES
-- -------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_db_obras_civiles_folio ON public.db_obras_civiles(obc_folio);
CREATE INDEX IF NOT EXISTS idx_db_obras_civiles_aco ON public.db_obras_civiles(obc_aco_numero);
CREATE INDEX IF NOT EXISTS idx_db_obras_civiles_fecha ON public.db_obras_civiles(obc_fecha);
CREATE INDEX IF NOT EXISTS idx_db_obras_civiles_estatus ON public.db_obras_civiles(obc_estatus);

CREATE UNIQUE INDEX IF NOT EXISTS uq_db_ordenes_trabajo_folio ON public.db_ordenes_trabajo(ot_folio);
CREATE INDEX IF NOT EXISTS idx_db_ordenes_trabajo_aco ON public.db_ordenes_trabajo(ot_aco_numero);
CREATE INDEX IF NOT EXISTS idx_db_ordenes_trabajo_fecha ON public.db_ordenes_trabajo(ot_fecha);
CREATE INDEX IF NOT EXISTS idx_db_ordenes_trabajo_estatus ON public.db_ordenes_trabajo(ot_estatus);

-- -------------------------------------------------------------
-- 5. PERMISOS PARA EL CLIENTE SUPABASE
-- -------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON public.db_obras_civiles TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.db_ordenes_trabajo TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

COMMIT;

-- -------------------------------------------------------------
-- 6. VALIDACIÓN FINAL
-- Debe devolver 0 filas.
-- -------------------------------------------------------------
WITH requeridas(tabla, columna) AS (
VALUES
('db_clientes_sucursales','suc_estado'),
('db_clientes_sucursales','suc_municipio'),
('db_usuarios','usu_correo'),
('db_obras_civiles','id_aco'),
('db_obras_civiles','id_sucursal'),
('db_obras_civiles','id_contacto'),
('db_obras_civiles','obc_folio'),
('db_obras_civiles','obc_fecha'),
('db_obras_civiles','obc_aco_numero'),
('db_obras_civiles','obc_cliente'),
('db_obras_civiles','obc_contacto'),
('db_obras_civiles','obc_sucursal'),
('db_obras_civiles','obc_direccion'),
('db_obras_civiles','obc_responsable_axia'),
('db_obras_civiles','obc_supervisor'),
('db_obras_civiles','obc_tipo_giro'),
('db_obras_civiles','obc_nombre_proyecto'),
('db_obras_civiles','obc_superficie_disponible'),
('db_obras_civiles','obc_superficie_adecuada'),
('db_obras_civiles','obc_planos_arquitectonicos'),
('db_obras_civiles','obc_requiere_maquinaria'),
('db_obras_civiles','obc_permisos'),
('db_obras_civiles','obc_observaciones_iniciales'),
('db_obras_civiles','obc_ejecucion_json'),
('db_obras_civiles','obc_pruebas_resultado'),
('db_obras_civiles','obc_pruebas_observaciones'),
('db_obras_civiles','obc_planos_acabados'),
('db_obras_civiles','obc_generacion_planos'),
('db_obras_civiles','obc_etapa_acabados'),
('db_obras_civiles','obc_obra_blanca'),
('db_obras_civiles','obc_evidencias_json'),
('db_obras_civiles','obc_preentrega_resultado'),
('db_obras_civiles','obc_preentrega_observaciones'),
('db_obras_civiles','obc_entrega_formal'),
('db_obras_civiles','obc_fecha_entrega'),
('db_obras_civiles','obc_observaciones_finales'),
('db_obras_civiles','obc_firma_cliente_base64'),
('db_obras_civiles','obc_firma_tecnico_base64'),
('db_obras_civiles','obc_estatus'),
('db_obras_civiles','creado_por'),
('db_obras_civiles','fecha_registro'),
('db_ordenes_trabajo','id_aco'),
('db_ordenes_trabajo','id_sucursal'),
('db_ordenes_trabajo','id_contacto'),
('db_ordenes_trabajo','ot_aco_numero'),
('db_ordenes_trabajo','ot_asunto'),
('db_ordenes_trabajo','ot_cliente'),
('db_ordenes_trabajo','ot_contacto'),
('db_ordenes_trabajo','ot_descripcion'),
('db_ordenes_trabajo','ot_esi'),
('db_ordenes_trabajo','ot_estatus'),
('db_ordenes_trabajo','ot_fecha'),
('db_ordenes_trabajo','ot_folio'),
('db_ordenes_trabajo','ot_jefe_operacion'),
('db_ordenes_trabajo','ot_numero_dias'),
('db_ordenes_trabajo','ot_numero_personas'),
('db_ordenes_trabajo','ot_partidas_json'),
('db_ordenes_trabajo','ot_prioridad'),
('db_ordenes_trabajo','ot_sucursal'),
('db_ordenes_trabajo','ot_supervisor'),
('db_ordenes_trabajo','creado_por'),
('db_ordenes_trabajo','fecha_registro')
)
SELECT r.tabla AS table_name, r.columna AS columna_faltante
FROM requeridas r
LEFT JOIN information_schema.columns c
  ON c.table_schema='public' AND c.table_name=r.tabla AND c.column_name=r.columna
WHERE c.column_name IS NULL
ORDER BY r.tabla, r.columna;
